// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektNET.Data;

#nullable disable

namespace ProjektNET.Migrations
{
    [DbContext(typeof(ProjektNETDbContext))]
    [Migration("20250427172124_ProjektNET")]
    partial class ProjektNET
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektNET.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("ProjektNET.Models.TrainerWorkoutClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.HasIndex("WorkoutClassId");

                    b.ToTable("TrainerWorkoutClasses");
                });

            modelBuilder.Entity("ProjektNET.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjektNET.Models.UserWorkoutClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutClassId");

                    b.ToTable("UserWorkoutClasses");
                });

            modelBuilder.Entity("ProjektNET.Models.WorkoutClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutClasses");
                });

            modelBuilder.Entity("TrainerWorkoutClass", b =>
                {
                    b.Property<int>("TrainersId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutClassesId")
                        .HasColumnType("int");

                    b.HasKey("TrainersId", "WorkoutClassesId");

                    b.HasIndex("WorkoutClassesId");

                    b.ToTable("TrainerWorkoutClass");
                });

            modelBuilder.Entity("UserWorkoutClass", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutClassesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "WorkoutClassesId");

                    b.HasIndex("WorkoutClassesId");

                    b.ToTable("UserWorkoutClass");
                });

            modelBuilder.Entity("ProjektNET.Models.TrainerWorkoutClass", b =>
                {
                    b.HasOne("ProjektNET.Models.Trainer", "Trainer")
                        .WithMany("TrainerWorkoutClasses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektNET.Models.WorkoutClass", "WorkoutClass")
                        .WithMany("TrainerWorkoutClasses")
                        .HasForeignKey("WorkoutClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("WorkoutClass");
                });

            modelBuilder.Entity("ProjektNET.Models.UserWorkoutClass", b =>
                {
                    b.HasOne("ProjektNET.Models.User", "User")
                        .WithMany("UserWorkoutClasses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektNET.Models.WorkoutClass", "WorkoutClass")
                        .WithMany("UserWorkoutClasses")
                        .HasForeignKey("WorkoutClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutClass");
                });

            modelBuilder.Entity("TrainerWorkoutClass", b =>
                {
                    b.HasOne("ProjektNET.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektNET.Models.WorkoutClass", null)
                        .WithMany()
                        .HasForeignKey("WorkoutClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserWorkoutClass", b =>
                {
                    b.HasOne("ProjektNET.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektNET.Models.WorkoutClass", null)
                        .WithMany()
                        .HasForeignKey("WorkoutClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektNET.Models.Trainer", b =>
                {
                    b.Navigation("TrainerWorkoutClasses");
                });

            modelBuilder.Entity("ProjektNET.Models.User", b =>
                {
                    b.Navigation("UserWorkoutClasses");
                });

            modelBuilder.Entity("ProjektNET.Models.WorkoutClass", b =>
                {
                    b.Navigation("TrainerWorkoutClasses");

                    b.Navigation("UserWorkoutClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
